### ISSUE TITLE
Get rid of returns in code

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#1007]
Should we get rid of `return` in the code? AFAIK `return` is just a mistake from the past and `pure` is preferred nowadays. `pure` resides in `Applicative` instead of `Monad`.

**Comment by eriksvedang** [comment]
Sure.

**Comment by scolsen** [comment]
They are equivalent, but from an economic perspective it makes more sense since `pure` will work in both monadic and applicative contexts.

As a fun fact, idris doesn't bother to define `return`, `mapM` and a bunch of other monadic functions that are covered by less powerful classes. The reason all the duplicates exist in Haskell is that monads were employed before the simpler/more specific classes that turn out to be distillations of some of the aspects of monads.
