### ISSUE TITLE
"Blit":able interface

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#1079]
Could be used to copy values using memcpy instead of walking the datastructure (e.g. an array of ints).

Similar to Rust:s `copy` trait (https://doc.rust-lang.org/std/marker/trait.Copy.html) ?

**Comment by jacereda** [comment]
By blittable do you mean "combine chunks of memory applying logical operations"?

**Comment by jacereda** [comment]
I see you used that term in https://github.com/carp-lang/Carp/commit/9e820df02a24e3700d178ecefc2d9ed894666f9b

Maybe something like `pod?` would be more appropriate?

**Comment by jacereda** [comment]
as in Plain Old Data...

**Comment by eriksvedang** [comment]
Yeah I was considering that too. The idea is that it's freely copyable (the deleter does nothing for the type) and "self contained", no pointers.

**Comment by eriksvedang** [comment]
Does anyone have any more ideas for names? I guess mirroring Rust would make a lot of sense here, to avoid too much confusion.

**Comment by scolsen** [comment]
> freely copyable

What does this mean precisely? That there's no need to copy individual members of the type? 

I left a comment on the delete PR, but I think the best case would be if we found some way to make this function not needed. Instead, `copy` could remain the sole interface, and implementers can decide how to do it, `memcpy` or whatever.

**Comment by eriksvedang** [comment]
> What does this mean precisely? That there's no need to copy individual members of the type?

With "freely copyable" I mean anything that only lives on the stack and where copying or deleting is taken care of by the C value type semantics.

There's currently no way to know if a type has these properties inside Carp. We had some special casing for it but it depended on knowing which ones of the built-in types are special. With the changes in https://github.com/carp-lang/Carp/pull/1061 there's very little difference between built-in and external types.

Now, in regards to `str`/`prn` we could just decide that they always take a `Ref`, since then we ensure that they won't delete anything passed to them (like `StringCopy.str` does, for example).

> Instead, copy could remain the sole interface

I agree that this is desirable, but I'm not convinced it's enough. For example, `Array` is not "freely copyable" but it's implementation of `copy` could be made a lot more efficient for the situations where it contains a type that is (via `memcpy`). I can't see how a single `copy` interface can provide enough information to implement this properly though – let me know if I'm missing something.

**Comment by scolsen** [comment]
> I agree that this is desirable, but I'm not convinced it's enough. For example, `Array` is not "freely copyable" but it's implementation of `copy` could be made a lot more efficient for the situations where it contains a type that is (via `memcpy`). I can't see how a single `copy` interface can provide enough information to implement this properly though – let me know if I'm missing something.

Ahh I see now—That makes sense, thanks for the explanation! 

Couldn’t this just be solved by implementing `copy` on concrete types? All the info we need comes from type distinctions anyway, right? So when structured data only provides structure one can do the right thing, when it doesn’t one does something else. That is, we’d provide several implementations of copy: 

```
(sig copy-generic (Fn [&(Array a)] (Array a)))
(implements copy copy-generic)
(defn copy-generic [x] (new-x (map copy x)))
;; memcpyable
(sig copy-arr-int (Fn [&(Array Int)] (Array Int)))
(implements copy copy-arr-int)
(defn copy-arr-int [x] (memcpy x))
```
The more specific type will always be selected, so the concrete case that’s memcpyable will be memcpy’d when that’s the type of the thing we’re working with. 

Isn’t the current type system powerful enough to just specialize for these cases? We might need to add support for having a deftemplate implement an interface, but otherwise I think this should just be solvable by defining copy for each concrete type you need it for. So, assuming `Array Foo` is copyable by some optimization that doesn’t need to walk the structure, you just implement `copy` against `Array Foo` and define it using the optimization in the function body. 

I might be missing some nuance here though.

**Comment by eriksvedang** [comment]
Yes, I think that works already. It should pick the most specialized signature if one is generic and one isn't. 

I think that approach will get out of hand quickly though, since you'd have to be very vigilant about all the array types that your program generates. Just imagine some generic function returning arrays, being used in a library...

**Comment by scolsen** [comment]
> Yes, I think that works already. It should pick the most specialized signature if one is generic and one isn't.
> 
> I think that approach will get out of hand quickly though, since you'd have to be very vigilant about all the array types that your program generates. Just imagine some generic function returning arrays, being used in a library...

Good point! You're right that having some separate interface in this case would help.

I guess my next question is whether the semantics of this interface should actually perform an operation or just be a predicate. e.g. we could do something like:

```
(definterface blitable (Fn [a] Bool))

(defn copy-array [arr] (if blitable (member arr...)))
```

But, it's interesting, because it's really a predicate on a type! Theoretically, we don't even need to access the array member in that body. So almost what we want here are type-level functions (like idris has)--in this case carrying some extra information about a type as it relates to another formal system (memory semantics).

One could also solve this at the type level:

```
(deftype (Blitable a) [of a])
;; or maybe
(deftype (Optimized a) [of a])
```

Then you only specialize for one particular type--`(sig optimized-copy (Fn [(f (Blitable a))] (f a)))`--but this is also probably less convenient than the interface approach since you'd have to remember to wrap your types in this type to leverage the optimization.

Really we want an [intersection type](https://en.wikipedia.org/wiki/Intersection_type) `Blitable` that is the intersection of values of all types that are freely copyable. We'd want some kind of way to say:

```clojure
(type Blitable Int Char ...)
(sig copy-optimized (Fn [(Array Blitable)] (Array Blitable)))
(implements copy copy-optimized)
;; somehow `Blitable` is matched against any of the types listed above, e.g.:
(copy [1 2 3]) ;; calls copy-optimized *unless* a fn copy on (Array Int) exists (more specific)
;; would work even though Int is not Blitable itself and Blitable has no constructors
;; it's a type synonym for multiple types
```

So that `Blitable` is any of those types.  The same thing is expressible if we add support for interface constraints and implement `blitable` as an interface as suggested:

```
(definterface blitable (Fn [a] a))
;; won't walk the structure.
(definterface copy-optimized ((blitable a) (Fn [(f a)] (f a))))
```

But in this case it's actually more limited as one would need to call `copy-optimized` explicitly instead of `copy` somewhere, and this isn't possible to do this in `copy` unless one moves up the blitable constraint to that function or unless we have some notion of "universal constraint".  I think in any case this notion of `blitability` defines a distinct type (which I guess is why Rust implements it as a trait).

I think the only way to support this without magic in the compiler that checks for the blitable interface is to properly support intersection types.

**Comment by hellerve** [comment]
We have that interface as of now, correct? Should this still be left open?
