### ISSUE TITLE
Dynamic closures named by `let` cannot refer to themselves

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#1133]
Currently, dynamic closures cannot refer to themselves if they were created in `let` bindings. I’m pretty sure this is related to #1101 and its followups:

Example:
```clojure
> (let [f (fn [x] (if (= x 1) x (f (dec x))))] (f 10))
Can't find symbol '"f"' at REPL:1:32.

Traceback:
(f 10) at REPL:1:46.
```

Cheers

**Comment by scolsen** [comment]
Good catch! This results from the fact that we no longer combine internal envs when resolving closures, since that caused a separate problem with shadowing argument bindings: #1126 has context.

This is tricky and is ultimately stemming from the fact that we handle both arguments and lets in the internal env--perhaps we should have a separate "let" env to resolve this--I think that also makes sense, since the let should have its own scope.
