### ISSUE TITLE
Discord community for Carp?

### ISSUE THREAD

**Issue by potatonomicon** [carp-lang/Carp#1204]
I didn't see this mentioned anywhere so I was wondering if there is any interest in creating a Discord server for Carp?
From what I have seen Discord is a little more common than Gitter and a little more structured and community oriented.
Would also be nice for those like me that would rather not use yet another chat service.

**Comment by eriksvedang** [comment]
Hi, thanks for the suggestion. I like Discord but I think Gitter makes a lot of sense for a project on Github since everyone can log in easily. Also, we have a lot of members there already so it's better to just keep things going, I'm not sure that many would move over. And splitting it up between to chat services will just be annoying.

**Comment by potatonomicon** [comment]
Fair enough, I wasn't actually aware you could log into gitter with a github account so now I just look like a dingus.
For clarity I wasn't implying we'd jump ship from gitter, just that we'd have a second chat.

**Comment by hellerve** [comment]
People who care about community never look like dinguses <3

**Comment by eriksvedang** [comment]
@potatonomicon No worries!
