### ISSUE TITLE
Another way to hang the compiler on recursive functions

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#1213]
I was experimenting with the fix for #349, and came up with this thing that still hangs:

```clojure
鲤 (sig g (Fn [Float] Float))
鲤 (defn g [x] (g))
```

Seems like the addition of the signature makes the difference, without it you get the appropriate warning.

**Comment by scolsen** [comment]
That makes sense, it’s somewhat related to the problem outlined in pr #1173. Basically what happens is a call to meta before a binding is defined immediately evaluates the binding and fixes its type to a type variable. It also winds up creating extra bindings for a single form, so when we look things up we might get the wrong one (in this case we would have a local g in the function environment that is typed correctly, and a global g that is typed as a type var). If we make it so that sig actually assigns the designated type to the binding that’ll fix this.  If we stop calling eval on meta-sets it’ll solve the double binding problem. 

Likely what’s happening here is that, during qualification, we somehow wind up finding the global g (created thanks to the meta set issue) instead of the local g, and then we lookup that symbol instead if the correctly typed local recursive one. 

Here are a few things to check related to fixing this throughly:

1. in qualify, make sure we are preferring local bindings first,
2. For meta-sets, make sure we dont immediately evaluate them, creating the binding in the incorrect environment. 
3. for sig, make sure we assign the type to the binding that’s in the sig form instead of a type var.
4. In the recursive typing, make sure our lookup is preferring local bindings (I think this should be correct already but it’d be good to double check).

**Comment by eriksvedang** [comment]
Great, all of that makes sense. 

`sig` always was kind of a hack, will be good to do something more principled.
