### ISSUE TITLE
Let binding in macro that shadows macro argument behaves weirdly

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#1280]
This is a weird one. Consider this macro:

```clojure
(defmacro x [y]
  (let [y y]
    y))
```

Ideally, the `let` binding shouldn’t do anything. Instead, the following happens when we use it:

```clojure
(x 'a) ; => y
```

That’s weird. What about more complicated expressions?

```clojure
(defmacro x [y]
  (let [y (if (symbol? y) 10 11)]
    y))
(x 'a) ; => (if (symbol? y) 10 11)
```

Apparently if a `let` binding is introduced and it shadows a macro argument—and only then—the right hand side of the let doesn’t get evaluated?! I’m not quite sure what the heck is going on here.

Cheers

**Comment by scolsen** [comment]
One hypothesis on what might be happening here: one could get this effect if the macro environment and let environment collide. My guess is there's an environment mismanagement somewhere where in rather than making the let a child of the macro environment, we're just replacing the `y` binding in the macro environment with the right hand side without calling the evaluator. Replacing `y` is correct in that case, but we should be calling evaluate somewhere that we aren't.

**Comment by hellerve** [comment]
Another fun fact: if I wrap this code in an `eval` it hangs!

**Comment by scolsen** [comment]
I found the problematic lines. When we resolve let's, we add a flag to make sure the evaluator knows to prefer local definitions over ones of wider scope with the same name.

```haskell
-- src/Eval. line 278
(finalCtx, evaledBody) <- eval newCtx body (PreferLocal (map (\(name, _) -> (SymPath [] name)) binds)) ResolveLocal
```

This then enters this branch in the evaluator:

```haskell
-- line 100
tryAllLookups (PreferLocal shadows) = (if spath `elem` shadows then (getLocal n) else (getDynamic)) <|> fullLookup
```

Since this is a shadow, we call out to `getLocal`

```haskell
-- line 118
getLocal name =
          do
            internal <- contextInternalEnv ctx
            (Binder _ found) <- maybeId (E.getValueBinder internal name)
            pure (ctx, Right (resolveDef found))
```

which then calls `resolveDef` after getting the binding (in this case the forms `y, (if... etc.`

```haskell
-- line 184
resolveDef (XObj (Lst [XObj DefDynamic _ _, _, value]) _ _) = value
    resolveDef (XObj (Lst [XObj LocalDef _ _, _, value]) _ _) = value
    resolveDef x = x
```

`resolveDef` just returns the value for let bindings `localDef` (lets) -- so the value itself is never evaluated in the course of this execution. That also explains why `eval` loops, since it'll just wind up continually returning `value` since this is a shadow.

It's not a problem during static evaluation since the value will be evaluated later anyway when it's reached in the function body. It's a problem for macros just because we don't evaluate the macro body.

Not sure about the best fix yet, but presumably we can add an eval call potentially--though there's a chance this might throw off some static cases

**Comment by scolsen** [comment]
The root of the problem might be with the environment handling for recursive bindings:

```
pure $ Right (fromRight (error "Failed to eval let binding!!") (bindLetDeclaration (newCtx {contextInternalEnv = origin}) n okX))
```

Here we reset the internal context to the *origin*, which doesn't have the evaluated values from `successiveEval`. This is not problematic for statics for the aforementioned reason that bindings are evaluated later anyway, but discarding the evaluation is problematic for macros....or something like that
