### ISSUE TITLE
libtinfo error

### ISSUE THREAD

**Issue by VarLad** [carp-lang/Carp#1360]
Carp starts but with this error

```
> carp
carp: /lib64/libtinfo.so.6: no version information available (required by carp)
Welcome to Carp 0.5.3
This is free software with ABSOLUTELY NO WARRANTY.
Evaluate (help) for more information.
>
```

libtinfo.so.6 is in the `/lib64` folder, which is a symlink to libtinfo.so.6.2

**Comment by scolsen** [comment]
Thanks for reporting, @VarLad! What platform is this on?

**Comment by VarLad** [comment]
Fedora Linux 35 x86_64

**Comment by scolsen** [comment]
Did you happen to run this from the prebuilt binary shipped in the release zip file, or did you build this from source?

**Comment by VarLad** [comment]
I tried the prebuilt binaries

**Comment by scolsen** [comment]
Ok, thanks! That makes sense. From what I've found it sounds like this error occurs when the dynamic library used for building the binary and the library on your system differ in their versions. We might have compiled Carp with v6 of libtinfo and your system might only have v5 or vice versa.

You could try updating libtinfo to the latest release available. Otherwise you can try installing Haskell stack and building from source (there are instructions in `docs/install`). I guess the longer term solution is to find out a more stable means of linking in the libraries we depend on in the prebuilt binaries. Probably we'll just have to statically link all code in the prebuilt binaries, but this will probably increase their size and overall resource usage, so we'll have to verify it doesn't increase by too much first.

**Comment by VarLad** [comment]
@scolsen sorry for the late reply
Like I said, I do have `/lib64/libtinfo`  and both versions as well
```
/usr/lib64> exa --long | grep "libtinfo"
lrwxrwxrwx@   15 root 23 Jul 02:05 libtinfo.so.5 -> libtinfo.so.5.9
.rwxr-xr-x@ 183k root 23 Jul 02:06 libtinfo.so.5.9
lrwxrwxrwx@   15 root 23 Jul 02:05 libtinfo.so.6 -> libtinfo.so.6.2
.rwxr-xr-x@ 191k root 23 Jul 02:06 libtinfo.so.6.2
```
I'll try building it from source

**Comment by VarLad** [comment]
@scolsen Building from Master works, but building from source didn't work
I'll try packaging Carp on Fedora Linux

**Comment by eriksvedang** [comment]
Version 0.5.4 is out, hopefully that fixes your issues without having to build from master.

**Comment by VarLad** [comment]
@scolsen Here's the Fedora packages https://copr.fedorainfracloud.org/coprs/varlad/carp-lang/
Should I make a PR to include this in the INSTALL.md?
