### ISSUE TITLE
REPL prompt is not `鯉` on Linux

### ISSUE THREAD

**Issue by t-sin** [carp-lang/Carp#1423]
Hi, I'm a newbie for this interesting language. When I ran Carp's REPL on my Ubuntu machine, the prompt string is not `鯉` sadly. I think that prompt is very nice so I want `鯉` to be a default prompt on Linux. (I know I can set the prompt via `Project.config`)

But, with the current implementation, `鯉` is set when running on mac. What the reason of this?

**Comment by eriksvedang** [comment]
Hi, and thanks for the question! I think the reason it's like this, is because only some terminal emulators on Linux support unicode. So there's a risk people will get gibberish output. On macOS the built in terminal supports unicode so it's a much safer bet there. So it's just a default to increase the likelihood that people get a nice first time experience. Hope that makes sense!

**Comment by t-sin** [comment]
Thank you for the answer, it makes sense! My question is resolved I close this issue.
