### ISSUE TITLE
[Feat Request] Exhaustive pattern-matching for `defn`

### ISSUE THREAD

**Issue by AZMCode** [carp-lang/Carp#1439]
As of currently one cannot define functions with pattern matching in the arguments. Allowing something like the following could be useful for ergonomics:
```
(defn fname [(Pair a b)] (+ a b))
```
Essentially desugaring to the following:
```
(defn fname [arg] (match arg (Pair a b) (+ a b)))
```

The pattern would need to be exhaustive to make this work, similar to patterns in lambdas

**Comment by AZMCode** [comment]
That is indeed quite useful.
Should this sort of functionality then be provided via library instead of through the language?

**Comment by hellerve** [comment]
It depends. I did it because I felt like it was a fun challenge, and honestly because programming in Carp is more fun to me than programming in Haskell.

It does have the limitation of introducing another form, though, because you can’t really override `defn`—well, I suppose you could, but I wasn’t quite daring enough.

We’ve had some conversations about what should be a macro and what shouldn’t be in the past. I’m a bit of a macro maximalist, so my view is skewed. The proper objective limitation is that macros are somewhat slow; `match-utils` actually has an optimization pass under the hood that reorders matches to limit how many branches are needed.[1] That optimization pass runs in macro world, and macro world is not exactly blazingly fast (it’s a tree-walking interpreter, essentially). In my opinion we should just bite the bullet and optimize it, but I don’t think anyone has the time or energy to do that at the moment.

[1] I’ve got a fun paper on that lying around if you’re _really_ interested.

**Comment by AZMCode** [comment]
Huh. I may not be at that level yet.
Perhaps there should be a protocol to determine what ultimately gets done with the language?
Are you the BDFL of this language?

**Comment by AZMCode** [comment]
Anyways, that's not a topic for this issue. Closing.
