### ISSUE TITLE
Implicit do in function bodies?

### ISSUE THREAD

**Issue by devn** [carp-lang/Carp#148]
Is there a reason why fern bodies don’t implicitly wrap the body with a do?

**Comment by eriksvedang** [comment]
The main reason is that the explicitness helps when reporting errors at type checking since the compiler "knows" wether you wanted to sequence multiple forms or just added some by accident. It also helps readability since you can often tell at a glance if the code is functional or imperative.

There is a `defn-do` macro that you can use if you want to.

**Comment by devn** [comment]
Agreed on the main reason, but I sort of disagree with it helping readability on functional vs. imperative.

If you open the body with `let`, `if`, etc. etc. and then `set!` somewhere inside, `do` as an indicator doesn't really "do" much for you.

Either way (slight tangent), are you familiar with Clojure's `io!`? https://clojuredocs.org/clojure.core/io!

I realize it's pretty Clojure-specific and you're not on a mission to recreate Clojure's feature set, but generally speaking it's a nice way of tagging code that does I/O so you don't inadvertently use it in a transaction. I wonder if something like this would ever be useful in Carp land.

Cheers, and feel free to close.

**Comment by phase** [comment]
Here's a fixed link to [io!](https://clojuredocs.org/clojure.core/io!)

**Comment by eriksvedang** [comment]
I wasn't aware of `io`, thanks for pointing that out. It's definitely true that imperative code can be hidden. I think it helps reading the code a little bit at least.
