### ISSUE TITLE
Is it mature yet? what about versionning?

### ISSUE THREAD

**Issue by piotr-yuxuan** [carp-lang/Carp#221]
> WARNING! This is a research project and a lot of information here might become outdated and misleading without any explanation. Don't use it for anything important!

This is very strong wording but it's 2-year old. Is it still valid? what about versioning this project? it would allow changes and improvements to be tracked. It would also tell people "it's 0.x.y, expect API changes and weird bugs to happen" or "it's 1.0.0 finally, let's give it a try \o/"

**Comment by eriksvedang** [comment]
Hello! Good question. I've kept the warning around because the compiler still isn't finished. It is actually versioned at 0.2.0 though this isn't very clearly communicated. See [/docs/Todo.org](/docs/Todo.org) for more information. When we release version 0.3.0 I'll update the warning to something less severe and also add a git tag + precompiled binaries.

Cheers,
Erik
