### ISSUE TITLE
Better reader macros

### ISSUE THREAD

**Issue by trans** [carp-lang/Carp#279]
I'd like to maker a suggestion to improve readability. Instead of the reader macros:

    &x ;; same as (ref x)
    @x ;; same as (copy x)

Use Unicode:

    ®x
    ©x

These can be represented in ASCII as

    (R)x
    (C)x

and a formatter can automatically transform them to Unicode when used (i.e. like Go's fmt tool).

I suggest this b/c `&` (usually thought of as "and"), in particular, is very misleading and ugly -- what we used to call a Perlism (LOL). `@` isn't as ugly but still very misleading (usually thought of as "at"). In fact I would be more inclined to intuit `@` as begin the reference, not the copy.

**Comment by trans** [comment]
Aside, is it my browser or does Github have a rather poor font for `@`, `®` and `©`?

**Comment by hellerve** [comment]
I’d personally prefer not to have Unicode in the core language at all, because it requires the user to use an editor configuration if they want to make it comfortable to type it (depending on their keyboard layout). Of course, most people have a config of some sort for the editor they prefer, but I `ssh` into a lot of servers where my config might not yet be, for instance. This is just an example case to illuminate why I don’t think requiring specialized configuration to edit code is useful (of course you’ll be more productive if you use a configuration, which is why I maintain the Vim plugin for Carp, but *requiring* one I deem counterproductive).

As for the reasoning: `&` means `take a reference` in C, C++, Go, and Rust. While it’s semantically only the same in Rust and Carp, I think this sort of precedent is a stronger argument for it than `ugly` is, which is subjective anyway. About misleading: I’d like to hear more about how you think it is misleading, given the precedents that I gave earlier?

`@` now is a different case. I honestly don’t care much about what glyph we should use. Again, what’s intuitive or not is wholly subjective. `@` can be read as you described it, but you could also read it as `give me the value at`. Only the `at` part is probably the same for everyone, the sentence before it is subjective.

I do take these kind of API issues seriously, but I think glyphs are, by design, only shorthand and, thus, leaky. Does that make sense?

As for your aside: I think their code font doesn’t render them very well. Monospace fonts often don’t have great Unicode glyphs. Yet another argument against Unicode in code? :P

**Comment by eriksvedang** [comment]
Thanks for the input! @hellerve's comment sums up my opinion very well, so no changes planned (except perhaps removing the one piece of unicode we have right now, the lambda symbol). In theory I like the idea with the copyright sign though, it's creative. But not gonna happen, sorry.

**Comment by trans** [comment]
It's too bad. I understand the precedence but & as "and" is far older and widely known precedence. Also for the unicode that's why you could type `(c)` instead. 

But in any case, would it be possible to define my own reader macros if I wanted to use © and ®?

**Comment by hellerve** [comment]
@trans we don’t have user-defined reader macros at the moment (and they aren’t on the roadmap), sorry :/

**Comment by OvermindDL1** [comment]
> I understand the precedence but & as "and" is far older and widely known precedence.

In general `&` as an unary operator in most languages that have references is a reference operation, `&` as a binary operator is a binary `and` in general, and at the type level `&` is generally a reference type.
