### ISSUE TITLE
ASL 2.0 | MIT | BSD | Boost

### ISSUE THREAD

**Issue by sirinath** [carp-lang/Carp#30]
Can you license this as a combination of:

 - ASL 2.0
 - MIT or 2 Clause BSD or Boost

for the compiler and

 - ASL 2.0
 - Boost

for the libraries. 

Also it might be an idea to triple license it using ASL 2.0, Boost, either MIT or 2-BSD for compiler and standard library.

**Comment by mkfifo** [comment]
Why?
What advantages do the proposed scheme have over the existing MPL?
and why the complex hybrid licensing involving 2-3 licenses spread over compiler and libraries?

**Comment by sirinath** [comment]
- Having ASL 2.0 licenses: The most free license is MIT but it does not have patent clause so it is safe to have this in combination with a more permissive license or languaging strategy used by MS where you have MIT in combination with a Patent Grant or what is used in Rust, [Flix](http://flix.github.io/) tha is MIT in combination with ASL 2.0
- MIT / BSD you will have to redistribute the license with your source when you use the standard libraries hence Boost is recommended or the licensing strategy used by Apple in Swift whereby which is ASL 2.0 with a runtime library exception.

Now Apple and MS are big companies and many of these exemptions get whitelisted or pre approved. In cases there are non standard exemptions then you might have to deal with lawyers to get the approval. 

Combining ASL 2.0, MIT, Boost you mitigate the patent issue and are very standard libraries which generally are pre approved and you do not have to add a dangling file MIT or ASL 2.0 text file even when you are using the standard library and may not be licensed under MIT or ASL 2.0.

**Comment by mkfifo** [comment]
FWIW I in no way speak for the creator(s) of Carp.

Your concern with the copy-left nature of MPL is valid in the case of wanting to use the language to make proprietary software, and modifying the language in order to do so - in which case ASL might be a next step to consider.

However because this is a lisp, modifying the actual implementation shouldn't be needed as much - you should be able to get there via extensive use of macros instead.
Any most modifications to the core *should* be upstreamable and shareable with the larger community.

I don't see the advantage to dual/hybrid licensing - unless you want compiler under ASL and libraries under MIT (or something equally permissive).

Your other concern seems to be with having the licenses pre-approved within large-organisations, this I cannot speak to.

I have no objections to a more permissive license, but I also have no issue with the current state.

It is also true that any licensing changes are easier when they are done sooner, as you will have to get the okay from each contributor.

**Comment by sirinath** [comment]
ASL 2.0 is fine with runtime library exception. E.g. swift license: https://github.com/apple/swift/blob/master/LICENSE.txt

**Comment by Piot** [comment]
Agreed, this should have a proper MIT license
https://opensource.org/licenses/MIT

**Comment by vyp** [comment]
@Piot MPL is a 'proper' license.

**Comment by sirinath** [comment]
Any thoughts on how to move forward in this?

**Comment by eriksvedang** [comment]
I'll leave it at the current license for now. May change it later when moving to a non-research, "production ready" state.

**Comment by sirinath** [comment]
In which case have a CLA so you change the license.

**Comment by eriksvedang** [comment]
Good point!

**Comment by mkfifo** [comment]
Worth mentioning that without a CLA, you generally require permission from every contributor to change the license.

OTOH a CLA may prevent some people from contributing - some people are constrained by contracts to not sign any CLAs (or not sign any without consulting a legal team).

**Comment by eriksvedang** [comment]
After being more informed about the various licenses I've decided that it's probably a good idea to switch to ASL 2.0.

If you're on the list, please reply to this issue with a +1 if you're fine with the license change. No reply before August 15th 2016 will be considered a +1.

Contributors:
* @bagucode  
* @paines
* @doublec
* @tomsmeding  
* @mkfifo 
* @dckc 
* @JonasG

**Comment by paines** [comment]
+1

**Comment by JonasG** [comment]
+1

**Comment by tomsmeding** [comment]
+1

**Comment by doublec** [comment]
+1

**Comment by mkfifo** [comment]
+1

**Comment by dckc** [comment]
+1 ASL 2.0

**Comment by Piot** [comment]
+1 MIT and BSD

**Comment by eriksvedang** [comment]
Carp now is on Apache Public License 2.0.

**Comment by dckc** [comment]
+1 ASL 2.0
