### ISSUE TITLE
Releases not tagged

### ISSUE THREAD

**Issue by jluttine** [carp-lang/Carp#301]
There are no releases tagged, but it says on readme that "we're currently working towards version 0.3.0 of the language". So I would expect there to be some earlier versions. Where can I find these versions? Would you like to consider tagging the versions so it'd be clear from the repository that to what each version refers to exactly?

**Comment by hellerve** [comment]
You’re absolutely right!

Though we use versioning to refer to states of the language, there are no releases yet, because that would imply that those versions should be released.

That being said, version 0.1.0 was the version of Carp that was written in C, which can still be obtained by checking out the `c` branch.  Version 0.2.0 was the rewrite that happened late last year; there is no tag or bracnh associated with that, AFAIK.

Version 0.3.0 will most definitely be tagged, however! Sorry if that’s confusing, but we want to avoid you checking out anything that’s severely outdated.

**Comment by jluttine** [comment]
Ok, thanks for the detailed answer! :+1:

**Comment by eriksvedang** [comment]
We now have a date for version 0.3.0 (July 1, 2019).
