### ISSUE TITLE
simplify keywords

### ISSUE THREAD

**Issue by samadadi** [carp-lang/Carp#307]
Please simplify some of the language commands. Isn't it better to have concise, expressive and simple-to-write command?

(system-include "math.h")   => (sysinclude "math.h") or (sysinc "math.h")
(local-include "math.h")       => (locinclude "math.h") or (locinc "math.h")
(register-type Apple)            => (regtype Apple)

**Comment by hellerve** [comment]
Personally, I value conciseness for my variables, but explicitness/specificity for functions.

That being said, the main argument I see for this kind of argument is “what value does it bring?” versus “what cost does it incur?”.

The value is debatable, as it is stylistic—you’d probably find a large amount of people preferring either aesthetic. You could also do the same by adding a macro for each of these builtins to conform to your stylistic needs; it wouldn’t be as pretty or convenient, but it would work. I understand, however, that that’s inferior and probably shouldn’t be done!

The cost, however, is not: you’d have to change all of the libraries, both in the standard library and elsewhere, that use this, and you’d invalidate all of the more static bits of documentation—blog posts and the like.

Admittedly, the cost is not tremendously high: you’d be able to appease the compiler by doing a search and replace over every codebase; writing this comment probably takes longer. Fixing all the blog posts is probably not easily feasible, but that’s written on another card.

I’d still say that the value isn’t worth the cost, at least to me. This might be biased because I’m not in favor of that change anyway! But I’d like to also float this kind of thinking so that we can think about whether the change is worth it as well as whether it’s valuable!

**Comment by eriksvedang** [comment]
Yes, these are not worth making shorter because they are pretty rare and clarity is more important than brevity for such cases. Cheers!
