### ISSUE TITLE
Incremental/JIT

### ISSUE THREAD

**Issue by Immortalin** [carp-lang/Carp#329]
Some Lisp-family languages like Julia hooks into LLVM and is able to incrementally compile/JIT the code. Any plans for this in Carp? Removing the C compiler dependency would be very useful.

**Comment by hellerve** [comment]
Thank you for your input! There are plans to consider LLVM in the later stages of the project. Personally I prefer C as a compilation target (see below if you want to see more)! But of course there are as many opinions out there as there are developers.

> Removing the C compiler dependency would be very useful.

I’m not sure where you are coming from here. I do agree that the less dependencies we have, the better, but I think more people have a C compiler installed than LLVM. But maybe you mean something else entirely?

About incremental compilation and JITing: I’d like to separate the two. Let’s talk about JIT compilation first.

I don’t think JITing would make much sense in the traditional JIT sense (or the one Julia uses, to my knowledge): we are already able to transform the entire program and there is no interpreter/runtime that could leverage Just-In-Time compilation to optimize its hot spots. Macros do not interfere with that, because they introduce less dynamicism than in Julia, and we are able to generate efficient source code despite their presence—at least as of yet. *DISCLAIMER: I know next to nothing about Julia, take everything I say with a grain of salt.*

Incremental compilation, however, would be very useful in the REPL context, as I see it. We could use that to run programs inside the REPL and maybe even use hot code swapping to make this more fun. This is definitely an underdeveloped area on the roadmap, and we should explore that when we find time to do so!

<details>
<summary>Reasons why I prefer C as a target (click to expand)</summary>

It is fairly straightforward to compile to C from Carp, and it is very simple to generate the appropriate C calls to facilitate a simple FFI. It all “just works”, but the C code is still inspectable and readable.

With LLVM on the other hand we will either have to generate IR or go the way of using one of the Haskell wrappers around LLVM. I’ve used the Haskell wrappers in a handful of projects over the years, and did not enjoy the experience at all. Don’t get me wrong, I appreciate the work the maintainers do and understand that this is a big task to take on, but even getting the wrapper to find LLVM was a pain. Case in point: I heard they’ve gotten better at catching up with recent versions of LLVM, but you used to have to install an outdated version of LLVM to link against. This would completely destroy the “seamless” experience that setting up Carp now is (sure, you need Stack and a C compiler, but most systems come with the latter, and you need something to compile the Haskell source code).

The C system is also already in place, and doesn’t seem to cause any problems. In fact, it’s a pleasure to work with! That might not be true in the future, and we should seriously reconsider any part of our infrastructure as soon as it causes trouble, but so far it’s been great! (Maybe Erik has differing opinions on this, since he works more at emitting code than I have)
</details>

**Comment by eriksvedang** [comment]
Basically @hellerve said everything already, here's my short version of it: If there are *good* Haskell bindings to LLVM at the time the language spec is done, this is definitely something we want. Until then I think the C backend has a lot of benefits and it's not a good idea to split our efforts.

A "historical" note is that the first version of the compiler had a lot of machinery for live evaluation, which complicated things a great deal (it didn't use LLVM for that though). So by removing that part we have been able to get pretty good results in other areas within a relatively short timespan. When I started the rewrite (current master branch) I actually investigated LLVM bindings from various languages for about a month until deciding that they are not very good, except from C++ (which makes sense). But I didn't want to write the compiler in C++, so here we are :)

**Comment by Immortalin** [comment]
For JIT/incremental it can be done in two stages i.e. an initial basic codegen followed by an optimizing stage while running. I think that's what WebAssembly and (IIRC) some JVM do.


I see, it would be great to have an alternative backend in future though. C is strongly tied with POSIX and it's associated culture, runtime specs etc. and this is not necessarily a positive for OS-level development (which I am assuming is possible with Carp?).

**Comment by Immortalin** [comment]
Can a dockerfile be provided for installation? This would greatly help ease adoption as not many people may want to install stack etc. especially if all they want to do is to try out Carp.

**Comment by Immortalin** [comment]
Another question regarding FFI, is is good enough to handle weird opaque C types created at compile-time with heavy pre-processor support? I haven't found a single non-C/C++ FFI that could handle embedding Guile and it's mutual callbacks.(the rust guile crate was the closest)

https://www.gnu.org/software/guile/docs/guile-tut/tutorial.html

**Comment by Immortalin** [comment]
For dockerfile, just fork this: https://hub.docker.com/_/haskell/

**Comment by hellerve** [comment]
I will provide a reply to your comment about JITing for now; the Dockerfile and C question I will answer separately (it is rather late around here):

> For JIT/incremental it can be done in two stages i.e. an initial basic codegen followed by an optimizing stage while running. I think that's what WebAssembly and (IIRC) some JVM do.

That’s true, but it requires a runtime, i.e. the JIT must be embedded in the binary. This is not a design goal for Carp—in fact, I’d classify it as an anti-goal. I don’t think it’s a bad idea for a language, I actually rather enjoy JITed languages, I just don’t think it suits the Carp use case and goals ver ywell.

**Comment by Immortalin** [comment]
@hellerve

**Comment by hellerve** [comment]
You mentioned me, but I’m afraid I don’t know what you expect me to write about. Do you need clarifications on anything?

**Comment by hellerve** [comment]
Oh, I see; it’s about the Dockerfile! I completely forgot about that (sorry)!

I’ll open an issue for this separately, to keep track of it.

As for the weird opaque C types: you can treat them as opaque from within Carp and define them without members, in which case Carp assumes nothing about them and treats them as black boxes. That means you can only pass them to C functions, but I guess that’s about what you would do from within C as well.
