### ISSUE TITLE
Feedback wanted: Passing lambdas by reference

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#330]
So... there's currently some memory bugs related to the standard Array functions (`endo-map`, `filter`, anything that is passed lambdas and is defined in ArrayTemplates.hs). The problem is that the lambdas are sent to these functions by value, and the functions don't delete the lambda themselves. This is easy enough to fix – should just take a couple of minutes really – but I'm not sure it's the best solution.

Since the lambdas themselves are not allowed to consume the things they have captured, you almost always (I think..?) want to pass them by reference and keep them around for as long as possible (to avoid having to create a new one, or copy existing ones). This would make a lot of functions that currently just take a function type i.e. `(Fn [Int] Int)` take a reference to the same function type instead: `(Ref (Fn [Int] Int))`. Calling something like endo-map would then require passing a reference to a function or lambda instead: `(endo-map &(fn [x] (* x x)) stuff)`. Kinda ugly but very explicit, like the rest of the memory management in Carp.

There are probably a few things that could be done to make all of this a bit more confortable – being able to call a reference to a function directly is one thing, for example – but the verbosity would increase a little bit in some cases, for sure. To keep it as clean as it is now would require the easy fix of just deleting the lambdas inside the Array functions. 

Also; note that this isn't about optimizing the way lambdas are passed around "under the hood", but rather the semantics of when a lambda should free its environment.

If anyone has any opinons, ideas or questions on this, I'm very happy to hear those!

**Comment by hellerve** [comment]
I think we shouldn’t special-case the Array functions, and that would mean passing them in by reference. That would increase consistency and reduce the amount of surprise for new users when they learn about the memory model, which I think is more important than shaving off a character from the function invocation!

But maybe there is more to it that I don’t quite understand yet?

**Comment by jburell** [comment]
To me it sounds like there are two questions here: #1) Who owns and disposes the lambda? #2) Does the lambda capture the environment by ref or val?

I don't know anything about the Carp memory model, but the README.md states that it does not use GC and that it tracks ownership, so I'm guessing something similar to Rust (although be it superficially). 

Is there some documentation of the memory/ownership model of Carp (other than the Haskell code)?

You both seem to be familiar with Rust, so this might be repetition, but if not, this is the short version of how Rust handles this issue (since you seem to be adopting a similar model):

In Rust lambdas are bound on creation either to a let variable or a function argument and follow that scope in order to determine lifetime (i.e the bound symbol or the function scope it was passed to). In Rust, lambas capture the environment by reference by default and by value explicitly (using a move-keyword, which is a bit of a hack i guess). Depending on the type of interaction with the environment the lambda inherits one or more of the three function traits (Fn, FnMut, FnOnce) used to mark the interaction as immutable, mutable or call once (often used for invocations that cannot be repeated due to it consuming objects etc).

**Comment by jburell** [comment]
I agree that for a Lisp it makes sense to be as implicit as possible. A lesser verbose annotation could be used also, like a different marker for the lambda or the captured references (if you want to mix). 

I will take a look at the document later. Could read the code also, but my only Haskell merit is completing the LYAH book a couple of years back so it might take some effort to dig through.

Talking about semantics only however I agree that the most important part here is how transferred/borrowed ownerships are communicated to the writer in order to be able to reason about the effects of invocation. I'm in the camp of verbosity before ambiguity, especially at systems level, but Lisp veterans might disagree.

**Comment by eriksvedang** [comment]
@jburell Thanks a lot for the input! I've looked quite a bit on the Rust solution and it's very nice to have our solution in Carp "reviewed" by people who know that language better than I do.

@hellerve I totally agree that there should be no special cases. One thing that I failed to mention is that all the other core functions also have this problem, except they actually delete the lambdas (because of proper insertion of deleters in the generated C code, this isn't the case in the templates). So they also consume the lambdas, which isn't really what we want in most cases, I think..?

**Comment by eriksvedang** [comment]
@hellerve Re-reading your comment I'm assuming that you're aware of this and that we agree that all of these functions should actually take refs to lambdas. This is actually a bit tricky to do right now... You could call functions like this: `((Function.copy f) arg1 arg2)` which would turn `f` into a ref, but that's not great, obviously. It seems like an ability to call functions even when they have the type `(Ref (Fn ...))` is needed for this to work out well...

**Comment by hellerve** [comment]
I did not know that references to functions cannot be called, that changes the semantics, of course.

I don’t mind either way of functions being owned by the callee or not; I just advocate consistency. Whatever way we use we should use everywhere. If we can’t, that sounds like a design flaw to me, API-wise.

**Comment by eriksvedang** [comment]
That meakes sense. I think I'll experiment with letting references be called and see if that can make things nicer. If not, I think the function being consumed is fine in most cases (and then I'll just fix the memory bugs in the functions generated by templates).

**Comment by eriksvedang** [comment]
Some more ramblings...

One kinda (?!) nice way to solve this is to add something that lets you say that the function you're calling should be a reference, like this:

`;; Calling a function normally
(defn call-me-with-123 [f] ;; f : (Fn [Int] Int)
    (f 123))`

`[1]
(defn call-me-with-123 [f] ;; f : (Ref (Fn [Int] Int))
    (*f 123))`

If not marking the call site (of `f` in this case) with some information about wether it expects a ref or not, the type needs to be more advanced (in Rust they have a `callable` trait, we would need an `interface`). This is doable, but the type system as it stands wouldn't help you out very much and there would be a lot of vague errors, I'm afraid (this could be improved of course, but that is a big job I was hoping to defer a while...). It would also feel pretty different from how usual Carp code handles refs/non-refs, so I think the directness of knowing exactly what you want at each call site is a better design (for Carp). 

Unfortunately it's a bit hard to do in a beautiful way (normal function application is so perfect in lisp, so there's not much wiggle room, syntax wise).

Here are some other alternatives:

`[2]
((deref f) 123)`

`[3]
(~f 123)`

`[4]
(call-ref f 123)`

Thoughts..? :)

**Comment by hellerve** [comment]
Having just done manual function copying in #331 and hating myself for it, I would love this feature! I like the tilde because it is lightweight. It could be just another reader macro around `(deref f)` for me.

<details>
<summary>Rambly aside</summary>
Another problem that I had was calling lambdas in loops. You can’t do this:
```clojure
(for [i 0 100]
   (do-something-with-array-on-lambda array f))
```

Because `f` is owned by the callee. But all of the base functions, in e.g. `Array`, take ownership over the lambda! The only way I can solve this at the moment is by copying *on every loop iteration*! That’s not super, and it should be obvious to the person looking at this code that this is completely valid. Now if we could only make the compiler/type system realize that also...
</details>

**Comment by eriksvedang** [comment]
Yeah, the tilde is probably the best since it won't interfere with symbols (`*` would be a lot more messy). I'll try this and keep it in the `lambda` branch for testing out.

**Comment by eriksvedang** [comment]
There's now a proof of concept in the `lambda` branch in the file `examples/temp.carp`.

**Comment by eriksvedang** [comment]
The [lambdas](https://github.com/carp-lang/Carp/tree/lambdas) branch now contains a solution to these issues, with the core library updated to use it. I'll merge it into master pretty soon, if no one voices any concerns. This will break most code that uses any kind of higher order function, passing functions around, etc.
