### ISSUE TITLE
Defining functions with def doesn't work

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#364]
Code:
```
(defn duplicate-arg [f]
  (fn [x] (f x x)))

(def double (duplicate-arg +))

(defn main []
  (println* (double 3)))
```
Error:
```
Unable to concretize '(def double (duplicate-arg +))' at line 4, column 1 in '.../dbg.carp'
```

**Comment by eriksvedang** [comment]
Annoying... I'll look into it!

**Comment by hellerve** [comment]
Interestingly, this works when we use `Int.+` instead.

This makes sense since `double` is a variable, and thus needs to be concrete rather than general, unlike a function.

The internal explanation is thus this:
- A `fn` on the top level is still a variable. We do `<some_type> double = <some_expr>` somewhere, and that means that `double` has to have exactly one type.
- A `defn` on the top level can generate multiple distinct bindings.

So the question is how to fix this? Should we special case `fn` variables or disallow this alltogether?

**Comment by eriksvedang** [comment]
Good questions, still not sure what to do about this.

**Comment by eriksvedang** [comment]
This seems to be related to heuristics for static code. It does work when calling the global variable from static code now. So perhaps we can add more heuristics to solve it.
