### ISSUE TITLE
Can't take reference to Int.MAX

### ISSUE THREAD

**Issue by opqdonut** [carp-lang/Carp#381]
```
(defn main []
  (println* &(Map.put (Map.create) "key" &Int.MAX)))
```
generates invalid C:
```
./out//main.c:3291:16: error: cannot take the address of an rvalue of type 'int'
    int* _13 = &INT_MAX; // ref
               ^~~~~~~~
1 error generated.
carp: callCommand: clang -fPIC -lm ./out//main.c -o "./out//Untitled"   -I.//core/  -g  (exit 1): failed
```

**Comment by hellerve** [comment]
Good find! This happens presumably because `INT_MAX` is a macro that expands to a number literal, which is an rvalue (of which you cannot take the address).

A first proposal for a solution would be to move away from using macros like that and define global variables in the Carp headers that get assigned the values from the macro. Then they’d be a proper lvalue, meaning we can take their address. I’m not sure whether this is always feasible, though, and any better solutions/proposals would be appreciated.
