### ISSUE TITLE
Is it possible to dynamically create a recursive function?

### ISSUE THREAD

**Issue by cnasc** [carp-lang/Carp#402]
For the sake of exercise, I'd like to return a recursive procedure based on some input.

```clojure
(use Int)
(defn a-test [n]
    (let [neato (fn [x]
                  (if (<= x 0)
                    1
                    (* n (neato (- x 1)))))] ;; Error here "couldn't find the symbol 'neato'"
      neato))
```

Evaluating this gives me an error, and I'm unsure if this is intended behavior and/or if there is a better or more idiomatic way to do this.

**Comment by eriksvedang** [comment]
Let bindings can only refer to earlier bindings in the let, so that's why this doesn't work. Perhaps it should, I don't think making it work is *too* hard. I don't have time to mess around with it at the moment though, so it would have to be your own side project :)

**Comment by hellerve** [comment]
*Technical answer*: Closures do not capture themselves, because the name is bound too late.

*Helpful answer*: If you define a function with `defn`, it has a name. If you define an anonymous function with `fn` it doesn’t know about its own name, because it is given to it after the function is defined. It can refer to any `fn` defined before it, though, like so:

```clojure
(defn a-test [n]
    (let [id (fn [x] x)
          neato (fn [x]
                  (if (<= x 0)
                    1
                    (* n (id (- x 1)))))]
      neato))
```

Note that this program is not very sensible, it’s just to show how a `fn` can refer to prior bindings.

*Technical aside*: I’m not sure whether this is “accidental design” or whether the language should allow that kind of program. The current generated code is a little too rigid for that I think, because the environment structure of the closure is defined before the closure itself is defined, meaning that we decided for one solution for the ckicken-and-egg problem, where this would maybe require the other order. I’m not 100% positive that that’s true, though!

**Comment by hellerve** [comment]
Oh, I didn’t see your comment, @eriksvedang! Sorry about that :)

**Comment by cnasc** [comment]
I figured it might be something like that. Do you think the solution would be to extend `let`, or to add a `letrec` construct?

**Comment by hellerve** [comment]
We could specialize `let` bindings on anonymous functions so they capture themselves. Whether that’s a good idea or create lifetime issues I’m not sure, though!

**Comment by fithisux** [comment]
I believe such a big let does not make sense. It is bad for code reviews or to maintainability. So, I am  thankful to the design that has it crashing. It is inline with what I would expect as a developer.

**Comment by cnasc** [comment]
@fithisux I agree that this style of `let` can be a bit hairy. But without a `letrec` or a Scheme-like internal definition construct (which would really just desugar into something like a `letrec`), there's no way to create a function on the fly that refers to itself.

**Comment by JAremko** [comment]
In Clojure lambdas can have names:

``` clojure
(let [foo (fn inner [...] ...)])
```
Here `inner` (aka `foo`) can call itself by the name `inner` or `recur`. The later one ensures tail call optimization.

**Comment by hellerve** [comment]
I like that solution, though it’s a little confusing having two names; maybe we could unify that somehow?

**Comment by JAremko** [comment]
I really like the concept of having `recur` as a special call that guaranties  tail call optimization.
Sometimes I'm not sure whether my code is optimized in this way but using `recur` makes sure that if it compiles it will be optimized. And having (fn <NAME> [...] ...) is also extremely useful especially when you work with nested lambdas.

**Comment by JAremko** [comment]
>  maybe we could unify that somehow?

How about [`letfn`](https://clojuredocs.org/clojure.core/letfn) ? Theoretically it can be united with `let`:
`[a <expr>]` - binding
`[(fn <name>...)`] also a binding but the variable name will be extracted from the `fn` form. Not sure about this. It might be over-complicated :thinking:

**Comment by JAremko** [comment]
@cnasc  How about [Y combinator](https://rosettacode.org/wiki/Y_combinator) :thinking:

**Comment by cnasc** [comment]
Y definitely would allow us to create recursive functions that don't know their own name. Might be a little cumbersome to write though!

**Comment by eriksvedang** [comment]
I don't think the Y combinator works in the type theory Carp is using either (which is something like System F, I think, kinda). The Y combinator is usually shown in untyped lambda calculus, but perhaps it works in some dependently typed variants too...

**Comment by eriksvedang** [comment]
So... do we want `letrec` in dynamic Carp, or should I close this?

**Comment by eriksvedang** [comment]
For the record, recursive functions defined with `defndynamic` work:

```clojure
(defndynamic f [x] (if (< x 1) 0 (+ x (f (- x 1)))))
```

**Comment by hellerve** [comment]
That is because the symbol lookup of dynamic functions happens at runtime (like in many dynamic languages). That makes sense to me, and is good and well.

I think `letrec` would thus only make sense in static code (“dynamically” here refers to act of creating a self-referential `fn` on the fly, not about the dynamic evaluator). I think _something_ needs to be done here, either a clearer error or allowing this. The error is definitely a shortcut, but that doesn’t mean that it is a worse design decision.

We could also add a closure to its own environment, which is going to be at least a little fiddly, but could be feasible.
