### ISSUE TITLE
`expand` hangs on modules

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#409]
There is a weird corner case in `expand` that seems to make it hang when modules are in the body of the expansion. To verify this bug, consider the following:

```clojure
(defmacro test [x] x)
(test T) ; fails, symbol not found
(expand '(test T)) ; => T
(defmodule T)
(test T) ; => T
(expand '(test T)) ; => hangs
```

Interestingly, this does not hang:

```clojure
(defmacro test [x] ())
(defmodule T)
(expand '(test T)) ; => ()
```

Which suggests to me that this issue has to do with the printing of modules or something like that?

Cheers

**Comment by eriksvedang** [comment]
I've been messing around with this one a fair bit now. It's very confusing. The infinite loop is in `expandAll` but I can't find where. It's almost like the data that is being evaluated has a self referencing part that is being evaluated, but I'm not sure if that's possible in Haskell?

**Comment by hellerve** [comment]
I also looked at that a bit, and saw that it came from `expandAll`, but didn’t look any further!

**Comment by tomsmeding** [comment]
This is probably already known to you, but I had a look into this and saw that the issue is indeed in `expandAll`, and in particular in the invocation `expanded == xobj`. `expandAllInternal` is called three times for `(test T)`-related XObj's, with `pretty` strings `(test T)`, `T` and `T`, in order. For the third one, the equality comparison doesn't seem terminate, or at least not very quickly.

It can be seen that something is awry by changing the explicit `Show` instance of `Binder` in `Obj.hs` to an automatically-derived one; after doing that, `show xobj` in the third case produces a string longer than 500 MB; I would not be surprised if it is infinitely long, but perhaps it just grows exponentially in something.

Unsurprisingly, in that case `xobj == xobj` also either loops or takes a really long time. Tracing the large section of the data structure a few layers deep, I found this path (for the third relevant invocation of `expandAllInternal`, which is the second where `pretty xobj == "T"`):

    case obj xobj of
      Mod c1 -> case envParent c1 of
        Just c2 -> case obj (binderXObj (envBindings c2 Map.! "BoolRef")) of
          Mod c3 -> case envParent c3 of
            Just c4 -> do
              traceM (c4 == c4)

Of course, the point is that that comparison also doesn't terminate. `c1` is quite alike `c3`, but _slightly_ larger, and `c2` is quite alike `c4`, but _slightly_ larger. Perhaps this helps in some way. :)

**Comment by eriksvedang** [comment]
Thanks a lot for investigating! 

I have been solving bugs like this before in the `expand ` function but there is something "extra" with this one.

**Comment by jacereda** [comment]
Looks like this is fixed, isn't it?

**Comment by eriksvedang** [comment]
It is! I wonder what fixed it....
