### ISSUE TITLE
Problems with Pattern examples in docs/LanguageGuide.md

### ISSUE THREAD

**Issue by jkleiser** [carp-lang/Carp#433]
This goes bananas:
```
鲮 (Pattern.matches? #"(\d+) (\d+)" "  12 13")
I can’t find any implementation for the interface `str` of type (λ [&Bool] String) at line 272, column 14 in '/Volumes/P3/Carp/core/Macros.carp'.

None of the possibilities have the correct signature:
    Array.str : (λ [(Ref (Array a))] String)
    Function.Arity0.str : (λ [(Ref (λ [] z))] String)
...
```
And this also have problems:
```
鲮 (Pattern.match #"(\d+) (\d+)" "  12 13")
I encountered an odd number of forms inside a `match` at REPL:1:1.
```
The example following that one repeats `Pattern.match` instead of using `Pattern.match-str`.

**Comment by hellerve** [comment]
The first program is problematic in the REPL because Carp tries to print the result out for you and doesn’t have the right function. If you want to try the program, you could write for instance `(defn main [] (println* (Pattern.matches? #"(\d+) (\d+)" "  12 13")))` to make sure it does exactly what you want—followed by a `:bx` for `(build)` and `(execute)`, respectively.

The second one is way worse. `Pattern.match`[doesn’t exist](http://carp-lang.github.io/Carp/core/Pattern.html), but the parser apparently tries to parse this as a `match` expression (which is used for pattern matching sum types, not for the pattern matching you’re currently doing). The parser should not try to interpret the expression as a `match` if it’s qualified with any module name; I’ll push a fix for that!

**Comment by hellerve** [comment]
Just to be clear: the first one is also a bug, albeit more of a conceptual one: should Carp try to wrap and print things implicitly for you in the REPL, and if so, how do we avoid confusing error messages if a function is missing?

**Comment by hellerve** [comment]
I’m also going to adjust the language guide; we haven’t touched that in a long time, and it’s probably out of date.

**Comment by eriksvedang** [comment]
I can close this, right? @hellerve
