### ISSUE TITLE
Unify signatures for `Array.aupdate` and struct update functions

### ISSUE THREAD

**Issue by hellerve** [carp-lang/Carp#471]
At the moment, the signatures for array updaters and struct updaters are different:

```
鲮 (load "Vector.carp")
鲮 (type Vector2.update-x)
Vector2.update-x : (λ [(Vector2 a), (Ref (λ [a] a))] (Vector2 a))
鲮 (type Array.aupdate)
Array.aupdate : (λ [(Array a), Int, (Ref (λ [&a] a))] (Array a))
```

Specifically the function being passed at the end. The function could take ownership over the element without any problems (since the element will be replaced anyway), but it only does in struct updaters. This could and should be unified.

Cheers

**Comment by eriksvedang** [comment]
This seems easy enough to fix for the 0.4.0 milestone, so I added it to it. Might require an update in the `StaticArray` module too, now.

**Comment by eriksvedang** [comment]
@rrruko Wanna do this one too? :) (it's the `Array.aupdate` that needs updating, it seems)

**Comment by eriksvedang** [comment]
This turned out to be quite tricky to implement using the primitives we have, I tried a small hack with dereferencing the reference (pointer) from `Array.unsafe-nth` but it turned out to be unsound. It's of course possible to implement using another template in ArrayTemplates, but we already have so many of those.
