### ISSUE TITLE
Array: Clarify `remove` semantics?

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#480]
(Sorry to generate so many issues (of varying legitimacy) lately, been putting the language through some paces!) 

It's quite possible I'm just misunderstanding how binding works, so this may be a non-issue, please let me know!

Currently, `Array.remove` removes elements from an array 'in-place' and returns the resulting array. While there's nothing wrong with this behavior, it does result in some scenarios in which the semantics are a bit muddled. Consider the following example:

```clojure
(def my-array (the (Array Int) (zero)) ;; initialize an array and bind it to my-array

(defn print-and-remove [] 
  (foreach [item my-array] 
    (do (IO.print item)
           (remove item @&my-array))))
```

At a glance, this seems to make intuitive sense: for each item in the array, print it, then remove it from the array, in place. I'd expect both functions in this case to be effectful types returning `()`. It is odd that we need to copy the bound array to manipulate it in place (on this point, I might be doing something wrong). 

If you try to define this, you'll get an error: 

```
I can’t match the types `(Array r17)` and `()` within `(do (let [item  ...  1)))`.

  (let [item (Array.nth xs i)] (do (IO.print item) (Array.remove item (copy (ref my-array))))) : (Array r17)
  At line 132, column 15 in '/Users/scottolsen/dev/Carp/core/Macros.carp'

  Statement in do-expression : ()
  At line 131, column 9 in '/Users/scottolsen/dev/Carp/core/Macros.carp'
```

This is only problematic when iterating over the array with foreach--if we change the types to match, this works fine:

```clojure
(defn print-and-remove [] 
  (foreach [item my-array] 
    (do (IO.print item)
           (set! my-array (remove item @&my-array)))))
```

But `remove` removes elements in place... so it's redundant to call `set!` on `my-array`!
...but also it's not, since we copied it to use it! (because that value was already owned by the binding). However, the initial reading of this code would suggest a redundancy and seems to conflict with my understanding of the term 'in-place'--I'd expect to not have to reset the value of a binding if the function operated on its value 'in-place'. But maybe this is a doc or personal issue? Maybe in-place is not the correct terminology here, or maybe I don't understand it properly?

Since the majority of effectful operations in Carp return `()` I would expect an in-place operation to be treated as effectful, remove the elements from a referenced array and return `()`, while a `copy-filter` based implementation (`copy-remove`?) can return the resulting array.

That said, it looks as though `endo-filter` also returns the resulting array and takes ownership. I'll admit that I'm not entirely sure what taking ownership means when the value is bound to a variable as in the case above--is the variable unbound or reset upon the function's taking ownership--then it makes sense that we'd have to set again--but if we're copying anyway...does it make sense? Perhaps I'm wrongheaded on this one, but thought I'd bring it up in case it's a potential point of confusion for others too! This may just be one that warrants a quick remediation of my understanding and notions, then we can move merrily on. 😅

**Comment by eriksvedang** [comment]
I understand that this is confusing, the documentation string should probably clarify "in place" a bit more – or use some other terminology there. What it means in this case is that the function `remove` won't copy the array internally but instead modify it and return the same instance. But yes, "in place" is used to describe the `!` family of functions to, that are effectful and return `()`. Do you have an idea for how to make the docs clearer in this regard?

I don't think the name `copy-remove` is good since it doesn't copy. We could have a `remove!` function though, that would help you write the code you want to write above. The problem with mixing owning functions and loops (like `foreach`) is that the memory analyser doesn't know what will happen inside the owning function so it can't just give away the same piece of memory in each iteration (the owning function might just eat it). So you often get cleaner code if you use a more functional approach, like `map` / `filter` / `reduce` when using the owning functions. 

Perhaps try that, and if you're not happy with the result we can add a `remove!` function?  Please let us know how it goes and let's discuss this further here, it's really great to hear about the actual experience of using the language since that gives us information on what ideas work and what needs to be adjusted!

**Comment by scolsen** [comment]
Thanks, Erik! Huge help. 

I can think a little bit about the docs and how to potentially make them clearer--it may just be a matter of applying certain terminology consistently--after your explanation, I can see how "in-place" applies well to both these cases (altering and returning the same instance, and for effectual alterations that return ()) so we may just need to figure out a way to further differentiate the two cases. I'll push forward using your advice and post any follow up questions here!

**Comment by eriksvedang** [comment]
Agreed, perhaps we should have a Terminology.md document with such concepts, each coupled with a brief description? Could be good to get more consistency in the doc strings.

**Comment by eriksvedang** [comment]
This document now exist here: https://github.com/carp-lang/Carp/blob/master/docs/Terminology.md
