### ISSUE TITLE
Top level bindings don't save their docstring (no module to save them to)

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#486]
Files like Macros.carp that does not put their definitions in a module but dump them in global scope don't get saved when generating documentation pages (using the `save-docs` command). There should be a way to scoop up these definitions and put them into "documentation modules" that have their own html page. We *could* just generate a "Global scope" module, but that would contain all the built in definitions in every project that generates docs, so that seems a bit annoying. 

Any ideas on how the user level interface for this extension to `save-docs` should work?

**Comment by scolsen** [comment]
Hm, I can think of two possible approaches:

* **The "shotgun" approach**: Add  a Bool argument to `save-docs` that when true, will save all the top-level project definitions (definitions in the project that have an empty Module path) in addition to the Modules passed as arguments. This is presumably an easy extension to use from the user's perspective, but has the downside you mentioned, Erik, of  more or less blindly saving docs for every definition in the project....and this is also problematic if the user is using some external lib, as presumably any top-level imports from the loaded libs would be captured too, so we'd have to differentiate those somehow as well. 
* **The "rifle" approach**: We can extend `save-docs` to take function names as arguments in addition to modules so that one can just do:
```
(doc foo "bar")
(defn foo [] ())
(save-docs MyModule foo)
```
And these docs can go into the main doc page for the project under a section titled "top-level definitions" or something similar, or we can render them in their own page.

This interface gets a little tedious if one has a bunch of top-level project definitions to document, as you'd have to pass each one as an explicit argument, but chances are in practice most code will be organized into modules regardless and one probably only needs to account for a select few top level defs.

Another option is to change `save-docs` to take filename arguments instead of Module names, and to simply document everything in the provided file, but I think the module name form is a lot nicer from a user's perspective since it aligns with the mechanisms carp provides for organizing code.

**Comment by jacereda** [comment]
I think I have a dead simple solution for this. Just enclose all the required top-level bindings in some module, say `GlobalGenerics`, and `(use GlobalGenerics)` afterwards.

**Comment by jacereda** [comment]
Maybe all definitions should belong to a module and the top-level should only be populated via `use`.

**Comment by eriksvedang** [comment]
That's definitely a possible solution... I think it makes sense for libraries to put all their functions into modules (maybe give a warning if they have added anything to the global space). 

So maybe just stuff all the core functions that don't belong anywhere into a module like in your PR and be done with it.

I still think that user level code should be allowed in global space, just because it's annoying to have to mess with modules if you just want to play around (especially at the REPL). We could of course wrap all REPL code in a module, but that would make it hard to put other modules directly in global scope.

**Comment by eriksvedang** [comment]
Someone had a great suggestion for how to solve this in the chat but I have forgotten, anyone who can remind me? :)

**Comment by hellerve** [comment]
I think allowing code in the global space is fine, but making it not emit docstrings is fine. We just have to document it. Then we could use @jacereda’s approach.

**Comment by eriksvedang** [comment]
But his approach requires the definitions to be inside a module, no?

**Comment by hellerve** [comment]
Only if you want to emit documentation for them, which is a fine restriction to me. In the REPL or any non-module context you’ll likely not emit documentation too often, I’d argue.

**Comment by eriksvedang** [comment]
Yeah, that'd be OK, for sure. But I think maybe a library author that creates some easy to access macro or something would like it though.

One more idea: Perhaps being able to grab all top level bindings that come from a certain file could work? Wouldn't be terribly hard to implement (and all definitions know what file they come from). Then they would all be put in a faux module called `Global` or something like that.

**Comment by hellerve** [comment]
You could also just do this as a library author:

```clojure
(defmodule MyLibraryMacros ;documentation lands here
   (doc x "hi!")
   (defmacro x [y z] (list '+ y z))
)
(use MyLibraryMacros) ; add it to the global scope yourself
```

**Comment by eriksvedang** [comment]
Oh, that's true! Nevermind then, lets keep the current behaviour (and lets document the global definitions in core)
