### ISSUE TITLE
UnificationFailure

### ISSUE THREAD

**Issue by jacereda** [carp-lang/Carp#521]
I'm getting the following error:

```
carp: UnificationFailure {unificationFailure = {a == (HitRecord a) (ord OrdMultiSym)} Nothing, Nothing in XObj {obj = Sym a Symbol, info = Nothing, ty = Nothing}, unificationMappings = fromList []}
CallStack (from HasCallStack):
  error, called at src/Concretize.hs:419:19 in CarpHask-0.3.0.0-inplace:Concretize
```

Looks like it's triggered by `checkForConflict` in `Constraints.hs`:

```
    if doesTypeContainTyVarWithName name otherTy
    then Left (UnificationFailure constraint mappings)
```

Is that supposed to be be raised by a problem in my code or unimplemented stuff?

**Comment by eriksvedang** [comment]
Not sure..! Will investigate asap.

**Comment by chrisosaurus** [comment]
@jacekschae what are you doing when you see this error? do you have reproduction steps?

**Comment by scolsen** [comment]
It's been a while, but I ran into a couple of these whilst playing with recursive type definitions.

Is your type in this case recursive? I can't quite tell from the error, but `a == (Hitrecord a)` makes it seem like it might be? ...or at least as though there's some other sort of use of type vars that Carp is not expecting. I had been investigating implementing support for expressing recursive types before I went traveling (afaik, Carp currently doesn't handle recursive type definitions such as `(deftype (My-list a) (Nil []) (List [a (My-list a)])` but there are ways around this).

**Comment by jacereda** [comment]
> what are you doing when you see this error? do you have reproduction steps?

It happens on a branch where I've changed the `Vector` functions to be generic, I'll try to isolate the problem and post a reproduction.

**Comment by jacereda** [comment]
> Is your type in this case recursive?

No, it was something like:

```
(deftype (HitRecord a)
    [
     t a
     p (Vector3 a)
     normal (Vector3 a)
     ])
```

**Comment by jacereda** [comment]
I simplified it and it's happening in master:

```clojure
(deftype (HitRecord a) [ t a ])
(deftype (CurrentHit a) [ hr (Maybe (HitRecord a)) ])
(defn hit [elts]
  (let [
        starting (CurrentHit.init (Maybe.Just (HitRecord.init 0.0)))
        closest (fn [cur h] cur)
        red (Array.reduce &closest starting elts)
        ]
    @(CurrentHit.hr &red)))
```

**Comment by jacereda** [comment]
Ok, simpler:

```clojure
(deftype (HitRecord a) [ t a ])
(deftype (CurrentHit a) [ hr (Maybe (HitRecord a)) ])
(defn hit [elts]
  (let [
        starting (CurrentHit.init (Maybe.Just (HitRecord.init 0.0)))
        ]
    @(CurrentHit.hr &starting)))
```

**Comment by scolsen** [comment]
Based on the error, it looks like the compiler is getting confused by the nested polymorphic types?Somewhere it's finding an instance of `a` that resolves to another polymorphic type taking `a`.

What happens if you simplify even further and change `CurrentHit` to `[hr (HitRecord a)]` instead of `Maybe (HitRecord a)`? Do you still get an error?

**Comment by jacereda** [comment]
> What happens if you simplify even further and change `CurrentHit` to `[hr (HitRecord a)]` instead of `Maybe (HitRecord a)`? Do you still get an error?

Removing the Maybe compiles fine.

**Comment by jacereda** [comment]
And if I rename the type variables from `a` to `b` everything is fine.

**Comment by scolsen** [comment]
Ok, so, it's an issue with the compiler's resolution of polymorphic types. If you use a different type variable instead of a, does that compile?

**Comment by scolsen** [comment]
Gotcha, so what's happening here is due to the fact that `Maybe a` is in the definition of Maybe and carp has no way to resolve encountering `Maybe a` where `a` contains the same type variable namely `HitRecord a`.

I think we can fix this by treating type variable symbols in the compiler differently. At present we just bring in the symbol as is (as you can see in the error)m resulting in collisions like this if the same variable happens to be used in a nested polymorphic definition. We should do some transformation to treat type variables uniquely in the right places even if they have the same representation.... or something like that

**Comment by scolsen** [comment]
So, this will be a *fairly*(??) significant change. I think we need to alter the reading of type signature XObjs so that we avoid treating typevars as plain old symbols and ensure they remain unique at each scope. Shouldn't be too bad since there's already a unique XObj for deftype--we just need to update how we handle instances of that particular XObj to differentiate between typ vars across different scopes.

**Comment by scolsen** [comment]
@eriksvedang, if you've got stuff goin' on I can take a shot at fixing this one

**Comment by eriksvedang** [comment]
@scolsen I'm on vacation so very little time to look into this now. Feel free to try to fix it! There are is a bunch of code for functions doing what I think is missing here for nested types, namely renaming type variables to unique names. Why does the structure of XObj need to change to facilitate this?

**Comment by scolsen** [comment]
> @scolsen I'm on vacation so very little time to look into this now. Feel free to try to fix it! There are is a bunch of code for functions doing what I think is missing here for nested types, namely renaming type variables to unique names. Why does the structure of XObj need to change to facilitate this?

I'll give it a shot. Sorry, I was being unclear--I didn't mean the structure of the XObj needs to change, just how we handle the particular XObj for this case, so all we should need to do, probably is use the functions you mentioned! 

Thanks! Enjoy your vacation :sunglasses:

**Comment by scolsen** [comment]
I've narrowed it down to `let` bindings, but am still working on determining where the precise problem lies.

**Comment by scolsen** [comment]
Somehow this fell off my radar. I just took a look at it and there's a really easy fix to stop the Unification Error...but it causes the sample program to hang. So, we need to make a slightly more significant change to the `checkForConflict` logic for vartys and structs to make this work.

**Comment by scolsen** [comment]
I got the program to run and type check just fine...but the fix breaks some other things. So I'll have to take a deeper look on this one.

**Comment by eriksvedang** [comment]
So, I investigated this a bit more and commented in #864 but this is a better place for the discussion, obviously.

The problem is that the function `concretizeType` (in `Concretize.hs:368`), when working on generic types will call `instantiateGenericSumtype` (I think the other one, `instantiateGenericStructType` should be problematic too but I haven't actually tried it).

`instantiateGenericSumtype` takes two types – the type we're trying to instantiate it to, and the original (generic) type but it fails to rename the type variable, instead just using the ones stored in the type environment. So there needs to be some substitution made before calling the function (since `instantiateGenericSumtype` will try to unify and the `a` in the generic type will collide with some other `a`).

This kind of substitution is already done when calling generic functions (including the ones that operate on sumtypes, otherwise we would have a lot more problems like this) using `renameVarTys`. The reason that this transformation isn't performed here is that `concretizeType` just looks up the types in the type environment and does nothing with them before passing them on to `instantiateGenericSumtype`.

I tried the simplest solution, just calling `renameVarTys` on both of the types, but unfortunately that wasn't enough. So I need to think more about the solution, any insight is very welcome! I would not be surprised if @scolsen beats me to it :) (You seem to have tried another aproach to solving this?)
