### ISSUE TITLE
Mac OSX build issues

### ISSUE THREAD

**Issue by mkfifo** [carp-lang/Carp#54]
My work on #24 has left some users ( @daveyarwood ) unable to build, whereas @eriksvedang is still able to build.

Opening issue to track progress.

I am working on setting up travis-ci for mac, I have #53 waiting which adds travis linux builds.

**Comment by mkfifo** [comment]
I lack a mac, so to help me I need:

mac osx install instructions for the deps

glfw3
rlwrap
libffi

I understand I can get libffi from homebrew or from our mac deps repo, but I would also like to know how our existing users are installing it.

I would also like some previously working mac osx build commands.

**Comment by mkfifo** [comment]
@daveyarwood please see #55 and test, let me know what works.

**Comment by daveyarwood** [comment]
See my comments on #55 -- tl;dr, it works 👍 but only if I provide `-DLIBFFI_INCLUDE_DIRS` and `-DLIBFFI_LIBRARIES` with the correct locations for my system.

I wonder if the `cmake` step can check in a number of possible locations (like the place where Homebrew put my libffi), and use it if it's there, otherwise fall back to what it's currently doing?

**Comment by mkfifo** [comment]
@daveyarwood awesome, so that is the first step, we have fixed the regression I accidentally introduced.

The next step will be to automate finding just like we do under Linux, we now have a carp-lang mac-deps-repo which has libffi within it - so worst case we can automate cloning of that to a known location and set the INCLUDE_DIRS and LIBRARIES paths automatically :)

**Comment by daveyarwood** [comment]
Awesome, sounds good!
