### ISSUE TITLE
[Feature Request] Better assertions in Test

### ISSUE THREAD

**Issue by scolsen** [carp-lang/Carp#689]
There are currently some limitations in the Test module that make it slightly tedious to write some tests. Namely, having to use refs in a lot of places, and lack of support for core Sumtypes such as `Maybe` and `Result`.

`Maybe` we can improve the support for core types?

**Comment by eriksvedang** [comment]
For sure, what's your take on this @hellerve ?

**Comment by hellerve** [comment]
The main problem is that `Maybe` and `Result` (and other sumtypes) contain owned types, but equality is usually defined on `ref`s. For instance, when comparing `(Maybe (Array Int))`:

```clojure
(= &(Maybe.Just [1]) &(Maybe.Just [2]))
```

It will try to look up a comparison for `(Array Int)` instead of `(Ref (Array Int))`. This is a general problem, but I think adding more functions or macros around that might make sense. I’m thinking of the following:

- Add some assertions: `assert-just`, `assert-nothing`, `assert-success`, `assert-error`.
- Add reference equality on members: `=&` will take the members by ref and check for their equality.
- Add those member reference equality checkers as assertions to the test library as well.

Those should address those concerns I think.

**Comment by hellerve** [comment]
We can close this as of #691, right?

**Comment by scolsen** [comment]
Sounds good!
