### ISSUE TITLE
Doc Request: no GC

### ISSUE THREAD

**Issue by bentxt** [carp-lang/Carp#70]
hi,
The first feature on the list: "Automatic and deterministic memory management".

Could this be elaborated a bit more extensively? What are your strategies? What does Carp different then all the other languages that use either manual or automatic memory management?

Thanks

**Comment by eriksvedang** [comment]
This document explains it a bit more: https://github.com/carp-lang/Carp/blob/master/docs/Memory.md
I will try to make an even nicer write-up there eventually, when the design has settled down more.

**Comment by eriksvedang** [comment]
The documentation has been extended a bit since you wrote your question. I'll leave this issue open until we have a nice writeup on all the details of the memory management in Carp.

**Comment by hellerve** [comment]
Now that we have [this blog post about the compiler](http://blog.veitheller.de/The_Carp_Compiler_(as_of_2017).html), maybe we can close this? Or maybe we should add it somewhere to the official documentation, if that is desirable? I’m obviously biased.

**Comment by eriksvedang** [comment]
We should definitely link to both of the blog posts somewhere in the documentation. Where is a good place you think? Perhaps the one about the compiler should be in the contributors document?

I don't think it closes the issue though, since there should still be a more "manual style" document in the docs that goes through exactly how memory management works from the programmers perspective (especially for people unfamiliar with Rust). `Memory.md` is supposed to be that but it's definitely lacking in precision and content.

**Comment by hellerve** [comment]
Fair enough. I’m not sure I’m equipped to write much about the memory subsystem, sadly.

Yes, I think the compiler should be in the Contributors document. The other one seems to fit into the Language Guide? The two documents then properly cross-reference each other.

**Comment by eriksvedang** [comment]
Sounds excellent.
I'll try to flesh out the memory document eventually.

**Comment by eriksvedang** [comment]
Not sure this is actually solved, but it's a bit vague so I'll close it.
