### ISSUE TITLE
XObj predicates

### ISSUE THREAD

**Issue by eriksvedang** [carp-lang/Carp#835]
There are tons of little predicates of type `XObj -> Bool` littered all over the code base. Perhaps it would be a good idea to put those into a separate module? (could maybe remove some duplicates or weird names in the process)

**Comment by TheAceShinigami** [comment]
I started taking a crack at this. I realized that you get a circular dependency because `XObj` is defined in Obj.hs the new module must depend on Obj.hs, but Obj.hs contains predicates, so it depends on the new module. I could do some hacky stuff and create a file with multiple modules, but I think it would be more sensible to just put the predicates in Obj.

**Comment by hellerve** [comment]
@TheAceShinigami yeah, that makes sense! I think putting that into `Obj` is a good workaround.

**Comment by scolsen** [comment]
Yep all those circular deps are an unfortunate but necessary evil.

Technically, haskell does have a an extension that allows solitary deriving declarations, which is actually all we need to break the circularity—but I think it’s ultimately simpler to just keep the module as is for now

**Comment by hellerve** [comment]
This can be closed through #882, right?
