### ISSUE TITLE
Why is Carp not based on Rust? (And a few other questions)

### ISSUE THREAD

**Issue by d4h0** [carp-lang/Carp#907]
Hi,

Carp looks very interesting, and I'm wondering why it was decided to transpile to C, instead of using Rust.

It seems it would have been much easier to create Carp this way.

Are there any limitations in Rust that prevented this?

Is my assumption correct, that it is easy to use Rust crates from Carp via a C ABI?

Also, is there any estimate when Carp will be ready for anything important? I'd love to use Carp :)

**Comment by scolsen** [comment]
@eriksvedang can answer this one, but I think it'd be cool to be able to support multiple compilation targets, C, Rust, whatever other language--thus one could have a "Rust Carp"--sort of analogous to what Clojurescript is for Clojure... I think it's possible to add support for something like that to the Carp compiler but it'd be a loooooong way out--it may also not be ideal from a design perspective.

**Comment by d4h0** [comment]
Thanks, @scolsen.

Another question I was thinking about is: I'm researching ways to create augmented reality apps right now. Would Carp be somehow usable for this in a reasonable way?

**Comment by hellerve** [comment]
About the AR question: since AR depends so heavily on huge libraries, many of them would have to be wrapped (at least the functions would need to be exposed); that’s a considerable bit of work that can be avoided in the languages those libraries are written in or where those wrappers already exist. It should be possible to wrap them and then write an app with Carp, but whether that qualifies as “reasonable” depends on whether writing such a wrapper sounds tedious or exciting for you! :)

**Comment by eriksvedang** [comment]
Compiling to Rust would give us more correctness checks so that would be great of course, but it wouldn't buy us much more. We want to catch the errors earlier (in the front-end / evaluator part, which is implemented in Haskell), having to echo the Rust compiler errors would be very confusing (they would not contain any Carp code). 

The choice of using C in the backend is just because it's flexible and easy to understand – we use it like an accessible kind of assembler, more or less. Also, since Carp isn't following the semantics of Rust exactly it's better to have a malleable target language (like C), or we might run into situations where it prevents us from implementing some feature. 

Hope that answers your first question!

**Comment by scolsen** [comment]
I think widespread compatibility is another benefit to having C be the target. A lot of people are interested in using Carp to program games and embedded software which may need to run on a bunch of different, possibly older, platforms--I'm not sure what stage Rust toolchain adoption is at now, but C is fairly ubiquitous, meaning we can run compiled Carp code on a lot of systems--of course you might still need to compile the carp source elsewhere, but at least once that's done you can copy over the resulting C to pretty much any system without hassle (assuming you use the right macros, headers, and everything else, of course).

**Comment by d4h0** [comment]
@hellerve: I assumed, because game dev seems to be a focus of Carp, that there is already a way to use some of the available game engines somehow. So that is not the case?

@eriksvedang: Thanks, that makes sense.

> but it wouldn't buy us much more

Another big benefit, in my opinion, would be that Rust crates could be used natively. I don't know much about the C ecosystem, but I'm assuming that there are fewer libs for high-level tasks than for Rust.

If not today, then most likely within the next one or two decades. It seems Rust is getting more popular very fast.

Another benefit would be the great tooling that Rust users enjoy.

**Comment by hellerve** [comment]
In the standard libraries there are wrappers around SDL and OpenGL.

Other than that, you can use the engines, but there is still the problem of telling Carp what functions there are in the libraries. There is a headerparser that can do this automatically for you, and that could work, but it probably won’t lead to very idiomatic interfaces, because it’s really just the C interfaces automatically translated into Carp. Making an actual wrapper will probably lead to a higher fidelity experience, but also requires someone to do the leg work.

**Comment by d4h0** [comment]
Thanks to everyone, for answering my questions! :)

Carp looks very interesting and I'd like to use it in the future for something.
